In [1]:
#1 implementacion de MPNeuron

import numpy as np

In [4]:
#Declaracion de la clase MPNeuron
class MPNeuron:
    def __init__(self):
        self.threshold = 0  # default threshold value
    def model(self, x):
        #input: [x1,x2,x3,...,xn][1,0]
        z = sum(x)
        return (z >= self.threshold)
    def predict(self,X):
        Y = []
        for x in X:
            result = self.model(x)
            Y.append(result)
        return np.array(Y)

In [5]:
#Instanciar clase
mp_neurona = MPNeuron()

In [6]:
mp_neurona.threshold = 2


In [10]:
mp_neurona.predict([[1,1,0,0],[1,1,0,1],[1,0,0,0]])

array([ True,  True, False])

In [11]:
#implementando compuerta and
mp_neurona.threshold = 2
mp_neurona.predict([[0,0,1,1],[0,1,0,1]])


array([ True,  True])

In [12]:
#implementando compuerta or
mp_neurona.threshold = 2
mp_neurona.predict([[0,0,1,1],[0,1,0,1]])

array([ True,  True])